kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: def-checks
  namespace: default
spec:
  deletionPolicy: Delete
  oasPath: https://raw.githubusercontent.com/matteogastaldello/azuredevops-oas3/79b82d804e475d57342fe7a396a826a505b1de88/approvalandchecks/pipelinechecks.yaml
  resourceGroup: azure.devops.com
  resource:
    kind: Checks
    # compareList:
    # - resource.id
    identifiers:
    - id
    - resource.id
    verbsDescription:
    - action: create
      method: POST
      path: /{organization}/{project}/_apis/pipelines/checks/configurations
    - action: findby
      method: GET
      path: /{organization}/{project}/_apis/pipelines/checks/configurations
      altFieldMapping:
        id: resource.id
    - action: delete
      method: DELETE
      path: /{organization}/{project}/_apis/pipelines/checks/configurations/{id}
    - action: get
      method: GET
      path: /{organization}/{project}/_apis/pipelines/checks/configurations/{id}
    - action: update
      method: PATCH
      path: /{organization}/{project}/_apis/pipelines/checks/configurations/{id}