kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: def-descriptors
  namespace: default
spec:
  deletionPolicy: Delete
  oasPath: https://raw.githubusercontent.com/krateoplatformops/azuredevops-oas3/main/graph/groups.yaml
  resourceGroup: azure.devops.com
  resource: 
    kind: Descriptor
    identifiers:
    - storageKey
    - value
    verbsDescription:
    - action: get
      method: GET
      path: /{organization}/_apis/graph/descriptors/{storageKey}