kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: def-pipelinepermissions
  namespace: default
spec:
  deletionPolicy: Delete
  oasPath: https://raw.githubusercontent.com/krateoplatformops/azuredevops-oas3/main/approvalandchecks/pipelinepermissions.yaml
  resourceGroup: azure.devops.com
  resource: 
    kind: PipelinePermission
    # identifiers: 
    # - 
    verbsDescription:
    - action: get
      method: GET
      path:  /{organization}/{project}/_apis/pipelines/pipelinepermissions/{resourceType}/{resourceId}
    - action: update
      method: PATCH
      path: /{organization}/{project}/_apis/pipelines/pipelinepermissions/{resourceType}/{resourceId}
    - action: create
      method: PATCH
      path: /{organization}/{project}/_apis/pipelines/pipelinepermissions/{resourceType}/{resourceId}


  