kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: def-queues
  namespace: default
spec:
  deletionPolicy: Delete
  oasPath: https://github.com/krateoplatformops/azuredevops-oas3/blob/main/environments/environments.yaml
  resourceGroup: azure.devops.com
  resource: 
    kind: Queue
    identifiers:
    - id
    - name
    verbsDescription:
    - action: get
      method: GET
      path: /{organization}/{project}/_apis/distributedtask/queues/{queueId}
      altFieldMapping:  # Optional: with the format <newField>: <oldField>
        id: queueId
    - action: findby
      method: GET
      path: /{organization}/{project}/_apis/distributedtask/queues
    - action: create
      method: POST
      path: /{organization}/{project}/_apis/distributedtask/queues
    - action: delete
      method: DELETE
      path: /{organization}/{project}/_apis/distributedtask/queues/{queueId}
      altFieldMapping:  # Optional: with the format <newField>: <oldField>
        id: queueId



  